services:
  web:
    build:
      dockerfile: ./infra/web/Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./config/nginx/tmp.html:/var/www/html/index.html
